apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtualization-ai-401
  labels: {{- include "virtualization-ai-401.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-operations-client
  labels: {{- include "virtualization-ai-401.labels" . | nindent 4 }}
automountServiceAccountToken: false
